services:
  - type: web
    name: BidMind
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: SECRET_KEY
        generateValue: true
      - key: MONGO_URI
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: GROQ_BASE_URL
        value: https://api.groq.com/openai/v1
      - key: SHARE_BASE_URL
        sync: false
